create or replace view view4js_ticket_order as
select RECORDID, TRADE_NO, CATEGORY, HFHPASS, DESCRIPTION2, STATUS, ORDER_TYPE, CINEMAID, RELATEDID, MOVIEID, ADDTIME, PLAYTIME, QUANTITY, TOTALCOST, SETTLE, UPDATETIME FROM TICKET_ORDER;


CREATE OR REPLACE VIEW VIEW_BAOCHANG_OPI AS
SELECT RECORDID,MPID,MOVIEID,MOVIENAME,CINEMAID,CINEMANAME,PREAMOUNT,PREPAY,ADDTIME,UPDATETIME,ROOMNAME,PLAYTIME,OPENTYPE,TYPE,SEATNUM,AMOUNT FROM WEBDATA.BAOCHANG_OPI;


ALTER TABLE "gsp"."place"
ADD COLUMN "pcid" varchar(20);
