package com.gewara.model.gsp;
// default package
// Generated Jul 31, 2013 2:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;

import com.gewara.enums.AdjustmentStatusEnums;
import com.gewara.model.BaseObject;
import com.gewara.util.DateUtil;

/**
 * Adjustment generated by hbm2java
 */
public class Adjustment extends BaseObject implements java.io.Serializable {
	private static final long serialVersionUID = -778108676262549193L;
	private Long recordId;
	private String tag;		//调整类型	  
	private String relateId;      //关联id
	private Double amount;// 调整金额
	private String reason; //调整原因
	private String comments;//调整说明
	private String operator;//操作人
	private Timestamp addTime;//添加时间
	private Timestamp updateTime;//更新时间
	private String status;//状态
	private String isSettled;
	private Double adjustNumber;//调整票数
	private String configId;
	private Long settleBillId;//关联结算单id
	private Integer version;
	private String isChannelSettled;
	private Long channelSettleBillId;
    private String attachFilePath;//附件路径
	/**
	 * @return the recordId
	 */
	public Long getRecordId() {
		return recordId;
	}
	public Adjustment(){
		this.version = 0;
	}
	
	/**
	 * @return the settleBillId
	 */
	public Long getSettleBillId() {
		return settleBillId;
	}
	/**
	 * @return the version
	 */
	public Integer getVersion() {
		return version;
	}
	/**
	 * @param version the version to set
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
	/**
	 * @param settleBillId the settleBillId to set
	 */
	public void setSettleBillId(Long settleBillId) {
		this.settleBillId = settleBillId;
	}
	/**
	 * @return the configId
	 */
	public String getConfigId() {
		return configId;
	}
	/**
	 * @param configId the configId to set
	 */
	public void setConfigId(String configId) {
		this.configId = configId;
	}
	/**
	 * @return the updateTime
	 */
	public Timestamp getUpdateTime() {
		return updateTime;
	}
	
	/**  
	 * @return isChannelSettled  
	 */
	public String getIsChannelSettled() {
		return isChannelSettled;
	}
	/**  
	 * @param set isChannelSettled 
	 */
	public void setIsChannelSettled(String isChannelSettled) {
		this.isChannelSettled = isChannelSettled;
	}
	/**  
	 * @return channelSettleBillId  
	 */
	public Long getChannelSettleBillId() {
		return channelSettleBillId;
	}
	/**  
	 * @param set channelSettleBillId 
	 */
	public void setChannelSettleBillId(Long channelSettleBillId) {
		this.channelSettleBillId = channelSettleBillId;
	}
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}
	
	
	/**  
	 * @return attachFilePath  
	 */
	public String getAttachFilePath() {
		return attachFilePath;
	}
	/**  
	 * @param set attachFilePath 
	 */
	public void setAttachFilePath(String attachFilePath) {
		this.attachFilePath = attachFilePath;
	}
	public Adjustment(String tag, String relateId, Double adjustNumber,  Double amount, String reason, String comments, String operator){
		this();
		this.tag = tag;
		this.relateId = relateId;
		this.adjustNumber = adjustNumber;
		this.amount = amount;
		this.reason = reason;
		this.comments = comments;
		this.operator = operator;
		this.addTime = DateUtil.getCurFullTimestamp();
		this.updateTime = addTime;
		this.status = AdjustmentStatusEnums.NEW.getStatus();
		this.isSettled = "N";
		
	}
	public Adjustment(String tag, String relateId, Double adjustNumber,  Double amount, String reason, String comments, String operator, String configId){
		this(tag, relateId, adjustNumber, amount, reason, comments, operator);
		this.configId = configId;
	}
	
	/**
	 * @return the reason
	 */
	public String getReason() {
		return reason;
	}
	/**
	 * @param reason the reason to set
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}
	/**
	 * @param recordId the recordId to set
	 */
	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}
	/**
	 * @return the tag
	 */
	public String getTag() {
		return tag;
	}
	/**
	 * @param tag the tag to set
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}
	/**
	 * @return the relateId
	 */
	public String getRelateId() {
		return relateId;
	}
	/**
	 * @param relateId the relateId to set
	 */
	public void setRelateId(String relateId) {
		this.relateId = relateId;
	}
	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return amount;
	}
	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	/**
	 * @return the comments
	 */
	public String getComments() {
		return comments;
	}
	/**
	 * @param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}
	/**
	 * @return the operator
	 */
	public String getOperator() {
		return operator;
	}
	/**
	 * @param operator the operator to set
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}
	/**
	 * @return the addTime
	 */
	public Timestamp getAddTime() {
		return addTime;
	}
	/**
	 * @param addTime the addTime to set
	 */
	public void setAddTime(Timestamp addTime) {
		this.addTime = addTime;
	}
	
	/**
	 * @return the isSettled
	 */
	public String getIsSettled() {
		return isSettled;
	}
	/**
	 * @param isSettled the isSettled to set
	 */
	public void setIsSettled(String isSettled) {
		this.isSettled = isSettled;
	}
	
	/**
	 * @return the adjustNumber
	 */
	public Double getAdjustNumber() {
		return adjustNumber;
	}
	/**
	 * @param adjustNumber the adjustNumber to set
	 */
	public void setAdjustNumber(Double adjustNumber) {
		this.adjustNumber = adjustNumber;
	}
	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}
	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}
	/* (non-Javadoc)
	 * @see com.gewara.model.BaseObject#realId()
	 */
	@Override
	public Serializable realId() {
		return recordId;
	}
}
