package com.gewara.model.gsp;
// default package
// Generated Jul 31, 2013 2:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;

import org.apache.commons.lang.StringUtils;

import com.gewara.model.BaseObject;
import com.gewara.util.DateUtil;

/**
 * GewaOrder generated by hbm2java
 */
public class GewaOrder extends BaseObject implements java.io.Serializable {

	private static final long serialVersionUID = -471528751030126102L;
	private String tradeno;
	private String tag;
	private Long relateId;
	private Long itemId;
	private Long playId;
	private Timestamp dealTime;
	private Timestamp useTime;
	private Timestamp syncTime;    
	private Integer quantity;
	private Double totalCost;
	private String otherInfo;
	private String isSettled;
	private Long checkBillId;
	private String orderStatus;  //paid_success, paid_return;
	private String isAdjusted;
	private String category;     //虚拟场次或其他系统对接场次
	private String outerId;      //第三方系统的外部ID
	private Timestamp updateTime; //上海系统updatetime
	private Timestamp takeTime;
	private String isChannelSettled;
	private Long channelCheckBillId;
	private String special;
	private String userBaochang;
	private Double discount;
	private Double alipaid;
	private Double reldiscount;
	private Double placeallowance;
	
	public GewaOrder() {
	}
	public GewaOrder(String tradeno, Long relateId, Long itemId, Long playId, Timestamp dealTime,  Timestamp useTime,
			Integer quantity, Double totalCost, String tag, String orderStatus, String otherInfo, String category, Timestamp updateTime){
		this.tradeno = tradeno;
		this.relateId = relateId;
		this.itemId = itemId;
		this.playId = playId;
		this.dealTime = dealTime;
		this.useTime = useTime;
		this.quantity = quantity;
		this.totalCost = totalCost;
		this.tag = tag;
		this.otherInfo = otherInfo;
		this.isSettled = "N";
		this.isAdjusted = "N";
		this.orderStatus = orderStatus;
		this.category = category;
		this.syncTime = DateUtil.getCurFullTimestamp();
		this.updateTime = updateTime;
		this.isChannelSettled = "N";
	}
	
	public Double getPlaceallowance() {
		return placeallowance;
	}
	public void setPlaceallowance(Double placeallowance) {
		this.placeallowance = placeallowance;
	}
	public Double getReldiscount() {
		return reldiscount;
	}
	public void setReldiscount(Double reldiscount) {
		this.reldiscount = reldiscount;
	}
	public Double getAlipaid() {
		return alipaid;
	}
	public void setAlipaid(Double alipaid) {
		this.alipaid = alipaid;
	}
	public Double getDiscount() {
		return discount;
	}
	public void setDiscount(Double discount) {
		this.discount = discount;
	}
	public String getUserBaochang() {
		return userBaochang;
	}
	public void setUserBaochang(String userBaochang) {
		this.userBaochang = userBaochang;
	}
	public String getSpecial() {
		return special;
	}
	public void setSpecial(String special) {
		this.special = special;
	}
	/**
	 * @return the updateTime
	 */
	public Timestamp getUpdateTime() {
		return updateTime;
	}
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}
	/**
	 * @return the outerId
	 */
	public String getOuterId() {
		return outerId;
	}
	/**
	 * @return the syncTime
	 */
	public Timestamp getSyncTime() {
		return syncTime;
	}
	/**
	 * @param syncTime the syncTime to set
	 */
	public void setSyncTime(Timestamp syncTime) {
		this.syncTime = syncTime;
	}
	/**
	 * @param outerId the outerId to set
	 */
	public void setOuterId(String outerId) {
		this.outerId = outerId;
	}
	/**
	 * @return the category
	 */
	public String getCategory() {
		return category;
	}
	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}
	/**
	 * @return the tradeno
	 */
	public String getTradeno() {
		return tradeno;
	}
	
	/**
	 * @return the otherInfo
	 */
	public String getOtherInfo() {
		return otherInfo;
	}
	/**
	 * @param otherInfo the otherInfo to set
	 */
	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}
	/**
	 * @param tradeno the tradeno to set
	 */
	public void setTradeno(String tradeno) {
		this.tradeno = tradeno;
	}
	/**
	 * @return the tag
	 */
	public String getTag() {
		return tag;
	}
	/**
	 * @param tag the tag to set
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}
	/**
	 * @return the relateId
	 */
	public Long getRelateId() {
		return relateId;
	}
	/**
	 * @param relateId the relateId to set
	 */
	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}
	/**
	 * @return the itemId
	 */
	public Long getItemId() {
		return itemId;
	}
	/**
	 * @param itemId the itemId to set
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}
	/**
	 * @return the playId
	 */
	public Long getPlayId() {
		return playId;
	}
	/**
	 * @param playId the playId to set
	 */
	public void setPlayId(Long playId) {
		this.playId = playId;
	}
	/**
	 * @return the dealTime
	 */
	public Timestamp getDealTime() {
		return dealTime;
	}
	/**
	 * @param dealTime the dealTime to set
	 */
	public void setDealTime(Timestamp dealTime) {
		this.dealTime = dealTime;
	}
	/**
	 * @return the useTime
	 */
	public Timestamp getUseTime() {
		return useTime;
	}
	/**
	 * @param useTime the useTime to set
	 */
	public void setUseTime(Timestamp useTime) {
		this.useTime = useTime;
	}
	/**
	 * @return the quantity
	 */
	public Integer getQuantity() {
		return quantity;
	}
	/**
	 * @param quantity the quantity to set
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	/**
	 * @return the totalCost
	 */
	public Double getTotalCost() {
		return totalCost;
	}
	/**
	 * @param totalCost the totalCost to set
	 */
	public void setTotalCost(Double totalCost) {
		this.totalCost = totalCost;
	}
	/**
	 * @return the isSettled
	 */
	public String getIsSettled() {
		return isSettled;
	}
	/**
	 * @param isSettled the isSettled to set
	 */
	public void setIsSettled(String isSettled) {
		this.isSettled = isSettled;
	}
	/**
	 * @return the checkBillId
	 */
	public Long getCheckBillId() {
		return checkBillId;
	}
	/**
	 * @param checkBillId the checkBillId to set
	 */
	public void setCheckBillId(Long checkBillId) {
		this.checkBillId = checkBillId;
	}
	/**
	 * @return the orderStatus
	 */
	public String getOrderStatus() {
		return orderStatus;
	}
	/**
	 * @param orderStatus the orderStatus to set
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}
	/**
	 * @return the isAdjusted
	 */
	public String getIsAdjusted() {
		return isAdjusted;
	}
	/**
	 * @param isAdjusted the isAdjusted to set
	 */
	public void setIsAdjusted(String isAdjusted) {
		this.isAdjusted = isAdjusted;
	}
	
	
	/**  
	 * @return takeTime  
	 */
	public Timestamp getTakeTime() {
		return takeTime;
	}
	/**  
	 * @param set takeTime 
	 */
	public void setTakeTime(Timestamp takeTime) {
		this.takeTime = takeTime;
	}
	
	
	/**  
	 * @return isChannelSettled  
	 */
	public String getIsChannelSettled() {
		return isChannelSettled;
	}
	/**  
	 * @param set isChannelSettled 
	 */
	public void setIsChannelSettled(String isChannelSettled) {
		this.isChannelSettled = isChannelSettled;
	}
	/**  
	 * @return channelCheckBillId  
	 */
	public Long getChannelCheckBillId() {
		return channelCheckBillId;
	}
	/**  
	 * @param set channelCheckBillId 
	 */
	public void setChannelCheckBillId(Long channelCheckBillId) {
		this.channelCheckBillId = channelCheckBillId;
	}
	@Override
	public Serializable realId() {
		return tradeno;
	}
	
	public boolean isRefund(){
		if (StringUtils.equals("paid_return", orderStatus))
			return true;
		return false;
	}
	
	public boolean isAdjust(){
		if (StringUtils.equals(this.isAdjusted, "Y"))
			return true;
		return false;
	}
}
