package com.gewara.model.gsp;

import java.io.Serializable;
import java.sql.Timestamp;

import com.gewara.model.BaseObject;
import com.gewara.util.DateUtil;

/**
 * Refundment generated by hbm2java
 */
public class Refundment extends BaseObject implements java.io.Serializable {

	private static final long serialVersionUID = -5058196801086932228L;

	private String tradeno;
	
	private String tag;
	private Long relateId; //³¡¹Ýid
	private Integer quantity;
	private Timestamp refundTime;
	private Double oldSettle;
	private Double newSettle;
	private String isSettled;
	private Long checkBillId;
	private Long playId;
	private Timestamp useTime;
	private String category;
	private String applyInfo;
	private String dealInfo;
	private Long settleBillId;
	private Integer version;
	private Timestamp syncTime;
	private String isChannelSettled;
	private Long channelCheckBillId;
	private Long channelSettleBillId;
	private String special;
	
	public Refundment() {
		this.version = 0;
	}
	
	public Refundment(String tradeno, String tag, Timestamp refundTime,
			Double oldSettle, Double newSettle, Long relateId, Long playId, Timestamp useTime, String category, int quantity,
						String applyInfo, String dealInfo) {
		this();
		this.tradeno = tradeno;
		this.tag = tag;
		this.refundTime = refundTime;
		this.oldSettle = oldSettle;
		this.newSettle = newSettle;
		this.isSettled = "N";
		this.relateId = relateId;
		this.playId = playId;
		this.useTime = useTime;
		this.category = category;
		this.quantity = quantity;
		this.applyInfo = applyInfo;
		this.dealInfo = dealInfo;
		this.syncTime = DateUtil.getCurFullTimestamp();
		this.isChannelSettled = "N";
	}
	
	public String getSpecial() {
		return special;
	}

	public void setSpecial(String special) {
		this.special = special;
	}

	/**
	 * @return the version
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * @return the syncTime
	 */
	public Timestamp getSyncTime() {
		return syncTime;
	}

	/**
	 * @param syncTime the syncTime to set
	 */
	public void setSyncTime(Timestamp syncTime) {
		this.syncTime = syncTime;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * @return the applyInfo
	 */
	public String getApplyInfo() {
		return applyInfo;
	}

	/**
	 * @return the settleBillId
	 */
	public Long getSettleBillId() {
		return settleBillId;
	}

	/**
	 * @param settleBillId the settleBillId to set
	 */
	public void setSettleBillId(Long settleBillId) {
		this.settleBillId = settleBillId;
	}

	/**
	 * @param applyInfo the applyInfo to set
	 */
	public void setApplyInfo(String applyInfo) {
		this.applyInfo = applyInfo;
	}

	/**
	 * @return the dealInfo
	 */
	public String getDealInfo() {
		return dealInfo;
	}

	/**
	 * @param dealInfo the dealInfo to set
	 */
	public void setDealInfo(String dealInfo) {
		this.dealInfo = dealInfo;
	}

	/**
	 * @return the category
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * @return the quantity
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity the quantity to set
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the playId
	 */
	public Long getPlayId() {
		return playId;
	}

	/**
	 * @return the useTime
	 */
	public Timestamp getUseTime() {
		return useTime;
	}

	/**
	 * @param useTime the useTime to set
	 */
	public void setUseTime(Timestamp useTime) {
		this.useTime = useTime;
	}

	/**
	 * @param playId the playId to set
	 */
	public void setPlayId(Long playId) {
		this.playId = playId;
	}

	/**
	 * @return the tradeno
	 */
	public String getTradeno() {
		return tradeno;
	}

	/**
	 * @param tradeno the tradeno to set
	 */
	public void setTradeno(String tradeno) {
		this.tradeno = tradeno;
	}

	/**
	 * @return the checkBillId
	 */
	public Long getCheckBillId() {
		return checkBillId;
	}

	/**
	 * @param checkBillId the checkBillId to set
	 */
	public void setCheckBillId(Long checkBillId) {
		this.checkBillId = checkBillId;
	}

	/**
	 * @return the tag
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * @param tag the tag to set
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * @return the relateId
	 */
	public Long getRelateId() {
		return relateId;
	}

	/**
	 * @param relateId the relateId to set
	 */
	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}

	/**
	 * @return the refundTime
	 */
	public Timestamp getRefundTime() {
		return refundTime;
	}

	/**
	 * @param refundTime the refundTime to set
	 */
	public void setRefundTime(Timestamp refundTime) {
		this.refundTime = refundTime;
	}

	/**
	 * @return the oldSettle
	 */
	public Double getOldSettle() {
		return oldSettle;
	}

	/**
	 * @param oldSettle the oldSettle to set
	 */
	public void setOldSettle(Double oldSettle) {
		this.oldSettle = oldSettle;
	}

	/**
	 * @return the newSettle
	 */
	public Double getNewSettle() {
		return newSettle;
	}

	/**
	 * @param newSettle the newSettle to set
	 */
	public void setNewSettle(Double newSettle) {
		this.newSettle = newSettle;
	}

	/**
	 * @return the isSettled
	 */
	public String getIsSettled() {
		return isSettled;
	}

	/**
	 * @param isSettled the isSettled to set
	 */
	public void setIsSettled(String isSettled) {
		this.isSettled = isSettled;
	}

	/* (non-Javadoc)
	 * @see com.gewara.model.BaseObject#realId()
	 */
	@Override
	public Serializable realId() {
		return tradeno;
	}

	/**  
	 * @return isChannelSettled  
	 */
	public String getIsChannelSettled() {
		return isChannelSettled;
	}

	/**  
	 * @param set isChannelSettled 
	 */
	public void setIsChannelSettled(String isChannelSettled) {
		this.isChannelSettled = isChannelSettled;
	}

	/**  
	 * @return channelCheckBillId  
	 */
	public Long getChannelCheckBillId() {
		return channelCheckBillId;
	}

	/**  
	 * @param set channelCheckBillId 
	 */
	public void setChannelCheckBillId(Long channelCheckBillId) {
		this.channelCheckBillId = channelCheckBillId;
	}

	/**  
	 * @return channelSettleBillId  
	 */
	public Long getChannelSettleBillId() {
		return channelSettleBillId;
	}

	/**  
	 * @param set channelSettleBillId 
	 */
	public void setChannelSettleBillId(Long channelSettleBillId) {
		this.channelSettleBillId = channelSettleBillId;
	}
	
}
