package com.gewara.model.gsp;
// default package
// Generated Jul 31, 2013 2:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;

import com.gewara.constant.SettleConstant;
import com.gewara.enums.CheckBillStatusEnums;
import com.gewara.model.BaseObject;
import com.gewara.util.DateUtil;

/**
 * SettlementBillId generated by hbm2java
 */
public class SettlementBill extends BaseObject implements java.io.Serializable, Comparable<SettlementBill>{
	private static final long serialVersionUID = 1166598449974922887L;
	private Long recordId;
	private Timestamp startTime;
	private Timestamp endTime;
	private String tag;
	private Long relateId;
	private String configId;
	private String status;
	private Timestamp updateTime;
	private String lastOperator;
	
	private Double orderTotalNumber;
	private Double orderTotalAmount;
	private Double refundTotalNumber;
	private Double refundTotalAmount;
	private Double unrefundTotalNumber;
	private Double unrefundTotalAmount;
	private Double adjustTotalNumber;
	private Double adjustTotalAmount;
	private Double previousRefundAmount;
	private Double previousRefundNumber;
	//异价总票数
	private Double diffPriceNumber;
	//异价总金额
	private Double diffPriceAmount;
	//卖出总票数
	private Double succTicketNumber;
	//卖出总金额
	private Double succTicketAmount;
	//请款单状态
	private String reqMoneyStatus;
	/**
	 * 卖品、通道费
	 */
	private Double applySettleNumber;
	private Double applySettleAmount;
	//特殊结算标示
	private String special;
	//场次类型
	private String playType;
	//是否记账
	private String hasJizhang;
		
	public SettlementBill(Timestamp startTime, Timestamp endTime, String tag, Long relateId, String configId){
		this.status = CheckBillStatusEnums.NEW.getStatus();
		this.updateTime = DateUtil.getCurFullTimestamp();
		this.lastOperator = "SYSTEM";
		this.startTime = startTime;
		this.endTime = endTime;
		this.tag = tag;
		this.relateId = relateId;
		this.configId = configId;
		this.orderTotalNumber = 0.0;
		this.orderTotalAmount = 0.0;
		this.refundTotalNumber = 0.0;
		this.refundTotalAmount = 0.0;
		this.unrefundTotalNumber = 0.0;
		this.unrefundTotalAmount = 0.0;
		this.adjustTotalNumber = 0.0;
		this.adjustTotalAmount = 0.0;
		this.previousRefundAmount = 0.0;
		this.previousRefundNumber = 0.0;
		this.diffPriceNumber = 0.0;
		this.diffPriceAmount = 0.0;
		this.succTicketAmount = 0.0;
		this.succTicketNumber = 0.0;
		this.reqMoneyStatus = SettleConstant.COMM_N;
		this.hasJizhang = SettleConstant.COMM_N;
	}
	public void initAggData(){
		this.status = CheckBillStatusEnums.NEW.getStatus();
		this.updateTime = DateUtil.getCurFullTimestamp();
		this.lastOperator = "SYSTEM";
		this.orderTotalNumber = 0.0;
		this.orderTotalAmount = 0.0;
		this.refundTotalNumber = 0.0;
		this.refundTotalAmount = 0.0;
		this.unrefundTotalNumber = 0.0;
		this.unrefundTotalAmount = 0.0;
		this.adjustTotalNumber = 0.0;
		this.adjustTotalAmount = 0.0;
		this.previousRefundAmount = 0.0;
		this.previousRefundNumber = 0.0;
		this.diffPriceNumber = 0.0;
		this.diffPriceAmount = 0.0;
		this.succTicketAmount = 0.0;
		this.succTicketNumber = 0.0;
	}
	
	public String getHasJizhang() {
		return hasJizhang;
	}
	public void setHasJizhang(String hasJizhang) {
		this.hasJizhang = hasJizhang;
	}
	public String getSpecial() {
		return special;
	}
	public void setSpecial(String special) {
		this.special = special;
	}
	/**
	 * @return the previousRefundNumber
	 */
	public Double getPreviousRefundNumber() {
		return previousRefundNumber;
	}

	/**
	 * @param previousRefundNumber the previousRefundNumber to set
	 */
	public void setPreviousRefundNumber(Double previousRefundNumber) {
		this.previousRefundNumber = previousRefundNumber;
	}

	/**
	 * @return the previousRefundAmount
	 */
	public Double getPreviousRefundAmount() {
		return previousRefundAmount;
	}

	/**
	 * @param previousRefundAmount the previousRefundAmount to set
	 */
	public void setPreviousRefundAmount(Double previousRefundAmount) {
		this.previousRefundAmount = previousRefundAmount;
	}

	/**
	 * @return the unrefundTotalNumber
	 */
	public Double getUnrefundTotalNumber() {
		return unrefundTotalNumber;
	}

	/**
	 * @param unrefundTotalNumber the unrefundTotalNumber to set
	 */
	public void setUnrefundTotalNumber(Double unrefundTotalNumber) {
		this.unrefundTotalNumber = unrefundTotalNumber;
	}

	/**
	 * @return the unrefundTotalAmount
	 */
	public Double getUnrefundTotalAmount() {
		return unrefundTotalAmount;
	}

	/**
	 * @param unrefundTotalAmount the unrefundTotalAmount to set
	 */
	public void setUnrefundTotalAmount(Double unrefundTotalAmount) {
		this.unrefundTotalAmount = unrefundTotalAmount;
	}

	public SettlementBill() {
	}

	/**
	 * @return the recordId
	 */
	public Long getRecordId() {
		return recordId;
	}

	/**
	 * @param recordId the recordId to set
	 */
	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	/**
	 * @return the configId
	 */
	public String getConfigId() {
		return configId;
	}

	/**
	 * @param configId the configId to set
	 */
	public void setConfigId(String configId) {
		this.configId = configId;
	}

	/**
	 * @return the startTime
	 */
	public Timestamp getStartTime() {
		return startTime;
	}

	/**
	 * @param startTime the startTime to set
	 */
	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return the endTime
	 */
	public Timestamp getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	

	/**
	 * @return the tag
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * @param tag the tag to set
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}


	/**
	 * @return the relateId
	 */
	public Long getRelateId() {
		return relateId;
	}

	/**
	 * @param relateId the relateId to set
	 */
	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}

	/**
	 * @return the orderTotalNumber
	 */
	public Double getOrderTotalNumber() {
		return orderTotalNumber;
	}

	/**
	 * @param orderTotalNumber the orderTotalNumber to set
	 */
	public void setOrderTotalNumber(Double orderTotalNumber) {
		this.orderTotalNumber = orderTotalNumber;
	}

	/**
	 * @return the orderTotalAmount
	 */
	public Double getOrderTotalAmount() {
		return orderTotalAmount;
	}

	/**
	 * @param orderTotalAmount the orderTotalAmount to set
	 */
	public void setOrderTotalAmount(Double orderTotalAmount) {
		this.orderTotalAmount = orderTotalAmount;
	}

	/**
	 * @return the refundTotalNumber
	 */
	public Double getRefundTotalNumber() {
		return refundTotalNumber;
	}

	/**
	 * @param refundTotalNumber the refundTotalNumber to set
	 */
	public void setRefundTotalNumber(Double refundTotalNumber) {
		this.refundTotalNumber = refundTotalNumber;
	}

	/**
	 * @return the refundTotalAmount
	 */
	public Double getRefundTotalAmount() {
		return refundTotalAmount;
	}

	/**
	 * @param refundTotalAmount the refundTotalAmount to set
	 */
	public void setRefundTotalAmount(Double refundTotalAmount) {
		this.refundTotalAmount = refundTotalAmount;
	}

	/**
	 * @return the adjustTotalNumber
	 */
	public Double getAdjustTotalNumber() {
		return adjustTotalNumber;
	}

	/**
	 * @param adjustTotalNumber the adjustTotalNumber to set
	 */
	public void setAdjustTotalNumber(Double adjustTotalNumber) {
		this.adjustTotalNumber = adjustTotalNumber;
	}

	/**
	 * @return the adjustTotalAmount
	 */
	public Double getAdjustTotalAmount() {
		return adjustTotalAmount;
	}

	/**
	 * @param adjustTotalAmount the adjustTotalAmount to set
	 */
	public void setAdjustTotalAmount(Double adjustTotalAmount) {
		this.adjustTotalAmount = adjustTotalAmount;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the updateTime
	 */
	public Timestamp getUpdateTime() {
		return updateTime;
	}

	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the lastOperator
	 */
	public String getLastOperator() {
		return lastOperator;
	}

	/**
	 * @param lastOperator the lastOperator to set
	 */
	public void setLastOperator(String lastOperator) {
		this.lastOperator = lastOperator;
	}

	
	/**  
	 * @return applySettleNumber  
	 */
	public Double getApplySettleNumber() {
		return applySettleNumber;
	}
	/**  
	 * @param set applySettleNumber 
	 */
	public void setApplySettleNumber(Double applySettleNumber) {
		this.applySettleNumber = applySettleNumber;
	}
	/**  
	 * @return applySettleAmount  
	 */
	public Double getApplySettleAmount() {
		return applySettleAmount;
	}
	/**  
	 * @param set applySettleAmount 
	 */
	public void setApplySettleAmount(Double applySettleAmount) {
		this.applySettleAmount = applySettleAmount;
	}
	
	/* (non-Javadoc)
	 * @see com.gewara.model.BaseObject#realId()
	 */
	@Override
	public Serializable realId() {
		return recordId;
	}

	@Override
	public int compareTo(SettlementBill sb) {
		return this.startTime.compareTo(sb.getStartTime());
	}
	
	public Double getDiffPriceNumber() {
		return diffPriceNumber;
	}
	public void setDiffPriceNumber(Double diffPriceNumber) {
		this.diffPriceNumber = diffPriceNumber;
	}
	public Double getDiffPriceAmount() {
		return diffPriceAmount;
	}
	public void setDiffPriceAmount(Double diffPriceAmount) {
		this.diffPriceAmount = diffPriceAmount;
	}
	public Double getSuccTicketNumber() {
		return succTicketNumber;
	}
	public void setSuccTicketNumber(Double succTicketNumber) {
		this.succTicketNumber = succTicketNumber;
	}
	public Double getSuccTicketAmount() {
		return succTicketAmount;
	}
	public void setSuccTicketAmount(Double succTicketAmount) {
		this.succTicketAmount = succTicketAmount;
	}
	public String getReqMoneyStatus() {
		return reqMoneyStatus;
	}
	public void setReqMoneyStatus(String reqMoneyStatus) {
		this.reqMoneyStatus = reqMoneyStatus;
	}
	public String getPlayType() {
		return playType;
	}
	public void setPlayType(String playType) {
		this.playType = playType;
	}
	
}
