package com.gewara.model.gsp;
// default package
// Generated Jul 31, 2013 2:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;

import com.gewara.enums.SettleCycleEnums;
import com.gewara.model.BaseObject;
import com.gewara.util.DateUtil;
import com.gewara.util.GewaLogger;
import com.gewara.util.WebLogger;

/**
 * SettleConfigId generated by hbm2java
 */
public class SettleConfig extends BaseObject implements java.io.Serializable {
	private static final GewaLogger logger = WebLogger.getLogger(SettleConfig.class);
	private static final long serialVersionUID = -4701229507263105472L;
	private String recordId;  //placeType + "," + placeId
	private String tag;
	private Long relateId;    //场馆id
	private String settleCycle;
	private Integer settleValue;
	private Integer offsetValue;
	private String settleBase;
	private String settleTime;
	private Timestamp firstSettle;
	private String status;
	private String zhangtaoNo;
	private String venderNo;
	private String venderName;
	//卖品是否结算，Y——是  N——否
	private String isGoodsSettle;
	private String applyUser;
	private String approveUser;
	
	private String openType;

	//是否结算给组织自己的组织供应商
	private String playType;
	//付款供应商编码
	private String payVenderNo;
	//付款供应商名称
	private String payVenderName;
	
	public SettleConfig() {
	}
	
	public String getPlayType() {
		return playType;
	}

	public void setPlayType(String playType) {
		this.playType = playType;
	}

	public String getPayVenderNo() {
		return payVenderNo;
	}

	public void setPayVenderNo(String payVenderNo) {
		this.payVenderNo = payVenderNo;
	}

	public String getPayVenderName() {
		return payVenderName;
	}

	public void setPayVenderName(String payVenderName) {
		this.payVenderName = payVenderName;
	}

	/**
	 * @return the recordId
	 */
	public String getRecordId() {
		return recordId;
	}
	
	/**
	 * @return the applyUser
	 */
	public String getApplyUser() {
		return applyUser;
	}
	/**
	 * @param applyUser the applyUser to set
	 */
	public void setApplyUser(String applyUser) {
		this.applyUser = applyUser;
	}
	/**
	 * @return the approveUser
	 */
	public String getApproveUser() {
		return approveUser;
	}
	/**
	 * @param approveUser the approveUser to set
	 */
	public void setApproveUser(String approveUser) {
		this.approveUser = approveUser;
	}
	/**
	 * @return the openType
	 */
	public String getOpenType() {
		return openType;
	}
	/**
	 * @param openType the openType to set
	 */
	public void setOpenType(String openType) {
		this.openType = openType;
	}
	/**
	 * @return the zhangtaoNo
	 */
	public String getZhangtaoNo() {
		return zhangtaoNo;
	}
	/**
	 * @param zhangtaoNo the zhangtaoNo to set
	 */
	public void setZhangtaoNo(String zhangtaoNo) {
		this.zhangtaoNo = zhangtaoNo;
	}
	/**
	 * @param recordId the recordId to set
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	/**
	 * @return the tag
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * @param tag the tag to set
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * @return the relateId
	 */
	public Long getRelateId() {
		return relateId;
	}

	/**
	 * @param relateId the relateId to set
	 */
	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}

	/**
	 * @return the settleCycle
	 */
	public String getSettleCycle() {
		return settleCycle;
	}

	/**
	 * @param settleCycle the settleCycle to set
	 */
	public void setSettleCycle(String settleCycle) {
		this.settleCycle = settleCycle;
	}
	/**
	 * @return the settleValue
	 */
	public Integer getSettleValue() {
		return settleValue;
	}

	/**
	 * @param settleValue the settleValue to set
	 */
	public void setSettleValue(Integer settleValue) {
		this.settleValue = settleValue;
	}



	/**
	 * @return the offsetValue
	 */
	public Integer getOffsetValue() {
		return offsetValue;
	}



	/**
	 * @param offsetValue the offsetValue to set
	 */
	public void setOffsetValue(Integer offsetValue) {
		this.offsetValue = offsetValue;
	}



	/**
	 * @return the settleBase
	 */
	public String getSettleBase() {
		return settleBase;
	}



	/**
	 * @param settleBase the settleBase to set
	 */
	public void setSettleBase(String settleBase) {
		this.settleBase = settleBase;
	}



	/**
	 * @return the settleTime
	 */
	public String getSettleTime() {
		return settleTime;
	}



	/**
	 * @param settleTime the settleTime to set
	 */
	public void setSettleTime(String settleTime) {
		this.settleTime = settleTime;
	}



	/**
	 * @return the firstSettle
	 */
	public Timestamp getFirstSettle() {
		return firstSettle;
	}

	/**
	 * @param firstSettle the firstSettle to set
	 */
	public void setFirstSettle(Timestamp firstSettle) {
		this.firstSettle = firstSettle;
	}


	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/* (non-Javadoc)
	 * @see com.gewara.model.BaseObject#realId()
	 */
	@Override
	public Serializable realId() {
		return recordId;
	}
	
	/**  
	 * @return isGoodsSettle  
	 */
	public String getIsGoodsSettle() {
		return isGoodsSettle;
	}
	/**  
	 * @param set isGoodsSettle 
	 */
	public void setIsGoodsSettle(String isGoodsSettle) {
		this.isGoodsSettle = isGoodsSettle;
	}
	public Timestamp calculateEndTime(Timestamp startTime){
		Timestamp end = null;
		if (SettleCycleEnums.TN.getType().equals(this.settleCycle)){
			end = DateUtil.addDay(startTime, 1);
		}else if (SettleCycleEnums.WEEKLY.getType().equals(this.settleCycle)){
			end = DateUtil.addDay(startTime, 7 * this.settleValue);
		}else if (SettleCycleEnums.MONTHLY.getType().equals(this.settleCycle)){
			end = DateUtil.getNextMonthFirstDay(startTime);
		}else if (SettleCycleEnums.MIDDLE.getType().equals(this.settleCycle)){
			int curDay = DateUtil.getDay(startTime);
//			if (curDay == 1)
//				end = DateUtil.addDay(startTime, 15);
//			else if (curDay == 16){
//				end = DateUtil.getNextMonthFirstDay(startTime);
//			}
			if(curDay >= 16){
				//至下月1号00:00:00
				end = DateUtil.getNextMonthFirstDay(startTime);
			}else{
				//至16日 00:00:00
				end = DateUtil.parseTimestamp(DateUtil.getYear(startTime) + "-" + DateUtil.getMonth(startTime) + "-16 00:00:00");
			}
		} else if(SettleCycleEnums.TENDAY.getType().equals(this.settleCycle)) {
			int curDay = DateUtil.getDay(startTime);
			if(curDay >= 20) { 
				end = DateUtil.getNextMonthFirstDay(startTime);
			} else if(curDay < 10) {
				end = DateUtil.parseTimestamp(DateUtil.getYear(startTime) + "-" + DateUtil.getMonth(startTime) + "-10 00:00:00");
			} else if(curDay >= 10 && curDay < 20) {
				end = DateUtil.parseTimestamp(DateUtil.getYear(startTime) + "-" + DateUtil.getMonth(startTime) + "-20 00:00:00");
			}
		}
		if (end == null){
			logger.error("end is null,settleconfig recordid is " + this.getRecordId());
			return null;			
		}
		
		end = DateUtil.parseTimestamp(
				DateUtil.format(end, "yyyy-MM-dd") + " " + settleTime + ":00", "yyyy-MM-dd HH:mm:ss"); 
		return end;
	}
	
	public boolean isTimeToSettle(Timestamp endTime){
		Timestamp now = DateUtil.getCurFullTimestamp();
		
		int addDay = SettleCycleEnums.TN.getType().equals(this.settleCycle) ? this.settleValue : this.offsetValue;
		Timestamp finalEnd = DateUtil.addDay(endTime, addDay);
		
		if (finalEnd.after(now))
			return false;
		
		return true;
	}
	
	/**
	 * @return the venderNo
	 */
	public String getVenderNo() {
		return venderNo;
	}
	/**
	 * @param venderNo the venderNo to set
	 */
	public void setVenderNo(String venderNo) {
		this.venderNo = venderNo;
	}
	/**
	 * @return the venderName
	 */
	public String getVenderName() {
		return venderName;
	}
	/**
	 * @param venderName the venderName to set
	 */
	public void setVenderName(String venderName) {
		this.venderName = venderName;
	}
	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
